// const muscleNameOptions = [
//     "wrists",
//     "wrist flexors",
//     "brachialis",
//     "feet",
//     "groin",
//     "core",
//     "hip flexors",
//     "spine",
//     "triceps",
//     "cardiovascular system",
//     "quads",
//     "calves",
//     "quadriceps",
//     "shins",
//     "sternocleidomastoid",
//     "grip muscles",
//     "wrist extensors",
//     "lower abs",
//     "inner thighs",
//     "ankles",
//     "chest",
//     "rear deltoids",
//     "shoulders",
//     "serratus anterior",
//     "abductors",
//     "lats",
//     "glutes",
//     "abdominals",
//     "hands",
//     "latissimus dorsi",
//     "rotator cuff",
//     "deltoids",
//     "upper chest",
//     "trapezius",
//     "ankle stabilizers",
//     "rhomboids",
//     "lower back",
//     "obliques",
//     "traps",
//     "upper back",
//     "biceps",
//     "pectorals",
//     "levator scapulae",
//     "forearms",
//     "adductors",
//     "abs",
//     "delts",
//     "hamstrings",
//     "soleus",
//     "back"
// ];

const muscleNameOptions = [
    "abs",
    "abdominals",
    "abductors",
    "ankles",
    "ankle stabilizers",
    "biceps",
    "back",
    "brachialis",
    "calves",
    "chest",
    "delts",
    "deltoids",
    "elliptical machine",
    "forearms",
    "feet",
    "glutes",
    "grip muscles",
    "groin",
    "hamstrings",
    "hands",
    "hip flexors",
    "inner thighs",
    "latissimus dorsi",
    "lats",
    "levator scapulae",
    "lower abs",
    "lower back",
    "medicine ball",
    "obliques",
    "pectorals",
    "quadriceps",
    "quads",
    "rear deltoids",
    "resistance band",
    "rhomboids",
    "rope",
    "rotator cuff",
    "serratus anterior",
    "shoulders",
    "shins",
    "skierg machine",
    "soleus",
    "spine",
    "sternocleidomastoid",
    "traps",
    "triceps",
    "trap bar",
    "upper back",
    "upper chest",
    "wrist extensors",
    "wrist flexors",
    "wrists"
];

// const equipmentNameOptions = [
//     "tire",
//     "elliptical machine",
//     "roller",
//     "olympic barbell",
//     "upper body ergometer",
//     "rope",
//     "barbell",
//     "medicine ball",
//     "stability ball",
//     "hammer",
//     "smith machine",
//     "dumbbell",
//     "ez barbell",
//     "stepmill machine",
//     "trap bar",
//     "stationary bike",
//     "skierg machine",
//     "bosu ball",
//     "resistance band",
//     "band",
//     "leverage machine",
//     "wheel roller",
//     "weighted",
//     "sled machine",
//     "assisted",
//     "body weight",
//     "cable",
//     "kettlebell"
// ];

const equipmentNameOptions = [
    "assisted",
    "band",
    "barbell",
    "bosu ball",
    "body weight",
    "cable",
    "dumbbell",
    "elliptical machine",
    "ez barbell",
    "hammer",
    "kettlebell",
    "leverage machine",
    "medicine ball",
    "roller",
    "resistance band",
    "sledge machine",
    "skierg machine",
    "smith machine",
    "stability ball",
    "stationary bike",
    "stepmill machine",
    "trap bar",
    "tire",
    "upper body ergometer",
    "weighted",
    "wheel roller"
];

// const bodyPartNameOptions = [
//     "lower legs",
//     "cardio",
//     "waist",
//     "lower arms",
//     "neck",
//     "upper legs",
//     "upper arms",
//     "back",
//     "chest",
//     "shoulders"
// ];

const bodyPartNameOptions = [
    "back",
    "cardio",
    "chest",
    "lower arms",
    "lower legs",
    "neck",
    "shoulders",
    "upper arms",
    "upper legs",
    "waist"
];

export { muscleNameOptions, equipmentNameOptions, bodyPartNameOptions };