const muscleNameOptions = [
    "abs",
    "abdominals",
    "abductors",
    "ankles",
    "ankle stabilizers",
    "biceps",
    "back",
    "brachialis",
    "calves",
    "chest",
    "delts",
    "deltoids",
    "elliptical machine",
    "forearms",
    "feet",
    "glutes",
    "grip muscles",
    "groin",
    "hamstrings",
    "hands",
    "hip flexors",
    "inner thighs",
    "latissimus dorsi",
    "lats",
    "levator scapulae",
    "lower abs",
    "lower back",
    "medicine ball",
    "obliques",
    "pectorals",
    "quadriceps",
    "quads",
    "rear deltoids",
    "resistance band",
    "rhomboids",
    "rope",
    "rotator cuff",
    "serratus anterior",
    "shoulders",
    "shins",
    "skierg machine",
    "soleus",
    "spine",
    "sternocleidomastoid",
    "traps",
    "triceps",
    "trap bar",
    "upper back",
    "upper chest",
    "wrist extensors",
    "wrist flexors",
    "wrists"
];

const equipmentNameOptions = [
    "assisted",
    "band",
    "barbell",
    "bosu ball",
    "body weight",
    "cable",
    "dumbbell",
    "elliptical machine",
    "ez barbell",
    "hammer",
    "kettlebell",
    "leverage machine",
    "medicine ball",
    "roller",
    "resistance band",
    "sledge machine",
    "skierg machine",
    "smith machine",
    "stability ball",
    "stationary bike",
    "stepmill machine",
    "trap bar",
    "tire",
    "upper body ergometer",
    "weighted",
    "wheel roller"
];

const bodyPartNameOptions = [
    "back",
    "cardio",
    "chest",
    "lower arms",
    "lower legs",
    "neck",
    "shoulders",
    "upper arms",
    "upper legs",
    "waist"
];

export { muscleNameOptions, equipmentNameOptions, bodyPartNameOptions };